// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-7YxBH0_n55QHp7PHSFjqYWW7lD_RDIk',
    appId: '1:131759964540:web:f5adc82c8d5dc07fd3e4f9',
    messagingSenderId: '131759964540',
    projectId: 'ct550-project',
    authDomain: 'ct550-project.firebaseapp.com',
    storageBucket: 'ct550-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGGC6_prD-ELevdEOyrxsQOLIGVBFbOm8',
    appId: '1:131759964540:android:71dd983ad79fad4dd3e4f9',
    messagingSenderId: '131759964540',
    projectId: 'ct550-project',
    storageBucket: 'ct550-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBf0P3ZXcNDRS6QhAh_FLPf1U-xqG1o-0',
    appId: '1:131759964540:ios:79281894db947a8fd3e4f9',
    messagingSenderId: '131759964540',
    projectId: 'ct550-project',
    storageBucket: 'ct550-project.appspot.com',
    iosClientId: '131759964540-cps2rcn44m10d46cjv2oficb7rigf328.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialVideo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBf0P3ZXcNDRS6QhAh_FLPf1U-xqG1o-0',
    appId: '1:131759964540:ios:79281894db947a8fd3e4f9',
    messagingSenderId: '131759964540',
    projectId: 'ct550-project',
    storageBucket: 'ct550-project.appspot.com',
    iosClientId: '131759964540-cps2rcn44m10d46cjv2oficb7rigf328.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialVideo',
  );
}
